name: EyeOnNature
favicon: null
layout_spectrum: 0.42629149346612394
typography_spectrum: 0.6823801186401397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12154728872701526
  lightness: 0.022248281864449382
  saturation: 0.5590706244111061
  rhythmicContrast: 0.8333365190774202
purpose: []
