name: Eye on Nature
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6823801186401397
title: My eye for all things nature
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e3358'
    - '#121702'
    - '#5f4d0b'
    - '#fbce2f'
    - '#9c841a'
  brandStrength: 0.12154728872701526
  lightness: 0.25
  saturation: 0.5590706244111061
  rhythmicContrast: 0.8333365190774202
purpose: []
